### PR TITLE
Added 2 screenshots

### PR DESCRIPTION
**Pull request by XusBadia**
Added screenshots for the top and the one with code + wireframing.

### CODE REVIEW

**Comment by Aagat** [comment]
Good job. Can you convert those pngs into compressed jpegs instead? It's low hanging optimization.

**Comment by XusBadia** [comment]
I checked with a JPG version and the filesize was the same, that's why I went with PNG. They are already optimized and compressed.

**Comment by Aagat** [comment]
Okay, even with jpeg quality set to something like 60%?

**Comment by XusBadia** [comment]
I tried it now and the filesize is almost the same. The files I don't think weight as much. For the final version, I can revisit them and see if I can improve them. But since we might change them in the future, I'd leave them as they are for now.

**Comment by Aagat** [comment]
Alright, sounds reasonable.

**Pull request merged**
